export const actionTypes = {
  TRENDING_FETCH_START: "TRENDING_FETCH_START",
  TRENDING_FETCH_SUCCESS: "TRENDING_FETCH_SUCCESS",
  TRENDING_FETCH_ERROR: "TRENDING_FETCH_ERROR",
  // Search
  SEARCH_FETCH_START: "SEARCH_FETCH_START",
  SEARCH_FETCH_SUCCESS: "SEARCH_FETCH_SUCCESS",
  SEARCH_FETCH_ERROR: "SEARCH_FETCH_ERROR",
};
